export const enum Paths {
    AUTH = '/auth',
    AUTH_GOOGLE = '/google',
    AUTH_REGISTRATION = '/auth/registration',
    AUTH_REBOOT_PASS = '/auth/confirm-email',
    AUTH_CHANGE_PASS = '/auth/change-password',
    MAIN_PAGE = '/main',
    RESULT = '/result',
    ERROR_LOGIN = '/result/error-login',
    SUCCESS_REGISTRATION = '/result/success',
    SUCCESS_CHANGE_PASSWORD = '/result/success-change-password',
    ERROR_NO_DATA_409 = '/result/error-user-exist',
    ERROR_OTHERS = '/result/error',
    ERROR_NO_EMAIL_AND_404 = '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL = '/result/error-check-email',
    ERROR_CHANGE_PASSWORD = '/result/error-change-password',
}
